apiVersion: v1
kind: Service
metadata:
  name: development
spec:
  ports:
    - port: 802
  selector:
    app: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: development
  template:
    metadata:
      labels:
        app: development
    spec:
      containers:
        - name: development
          image: gitlab.sdu.dk/semester-project-e2022/team-7-media-streaming/media-streaming-backend:latest
          ports:
            - containerPort: 802
      imagePullSecrets:
        - name: sdugitlab
