apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\happy\scoop\apps\kompose\current\kompose.exe convert -f docker-compose.yml -o ./kompose/
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
    - name: "802"
      port: 802
      targetPort: 802
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
