apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\happy\scoop\apps\kompose\current\kompose.exe convert -f docker-compose.yml -o ./kompose/
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-interface
  name: mongo-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-interface
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\happy\scoop\apps\kompose\current\kompose.exe convert -f docker-compose.yml -o ./kompose/
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: mongo-interface
    spec:
      containers:
        - env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo
          image: mongo-express
          name: mongo-interface
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
