apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      name: backend
  template:
    metadata:
      labels:
        app: backend
        name: backend
    spec:
      containers:
      - env:
        - name: DB_URL
          value: mongodb://mongo-svc:27017
        image: gitlab.sdu.dk:5050/semester-project-e2022/team-7-media-streaming/media-streaming-backend:1.0.12
        name: backend
        ports:
        - containerPort: 802
          name: backend-http
        resources:
          limits:
            cpu: 300m
            memory: 200Mi
          requests:
            cpu: 150m
            memory: 100Mi
      imagePullSecrets:
      - name: sdugitlab
