apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 2
  selector:
    matchLabels:
      name: dbui
  template:
    metadata:
      labels:
        name: dbui
    spec:
      containers:
      - env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo-svc
        image: mongo-express:latest
        name: mongo-express
        ports:
        - containerPort: 8081
          name: dbui-http
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
